version: '3.9'
services:
  db:
    image: mysql:8.2.0
    container_name: igrejapentecostalreformada-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: lucasadmin3010
      MYSQL_USER: lucas
      MYSQL_PASSWORD: lucasadmin3010
      MYSQL_DATABASE: igrejapentecostalreformada
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - ipr-network
  igrejapentecostalreformada-api:
    image: lspeixotodev/igrejapentecostalreformada-api
    container_name: igrejapentecostalreformada-api
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/igrejapentecostalreformada?useTimezone=true&serverTimezone=America/Sao_Paulo
      SPRING.DATASOURCE.USERNAME: lucas
      SPRING.DATASOURCE.PASSWORD: lucasadmin3010
    ports:
      - "80:80"
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - ipr-network
networks:
  ipr-network:
    driver: bridge